name: Frida Gadget Injector (Interaction Only)

on:
  push:
    branches:
      - main

jobs:
  patch-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Python
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          # Install Python dependencies
          pip install frida-gadget

          # Install apktool and its dependencies
          sudo apt-get update
          sudo apt-get install -y default-jdk
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          chmod +x apktool.jar
          sudo mv apktool.jar /usr/local/bin/apktool.jar
          echo '#!/bin/bash' | sudo tee /usr/local/bin/apktool > /dev/null
          echo 'java -jar /usr/local/bin/apktool.jar "$@"' | sudo tee -a /usr/local/bin/apktool > /dev/null
          sudo chmod +x /usr/local/bin/apktool

      - name: Create Frida Gadget Configuration File (Listen Only)
        run: |
          echo '{ "interaction": { "type": "listen", "address": "0.0.0.0", "port": 27042, "on_port_collision": "fallback" } }' > frida-gadget.config
          
      - name: Download APK from Hardcoded URL
        run: |
          APK_URL="https://files.catbox.moe/qswufu.apk" # <--- REPLACE THIS WITH YOUR APK URL
          curl -L -o original.apk "$APK_URL"

      - name: **[DIAGNOSTIC] Check Filesystem Before Injection**
        run: |
          echo "Listing files in current directory:"
          ls -l
          echo "---"
          echo "Contents of frida-gadget.config:"
          cat frida-gadget.config
          echo "---"

      - name: Run Frida Gadget injection
        id: frida_inject
        run: |
          frida-gadget original.apk --arch arm64 --no-res --sign --config frida-gadget.config

      - name: Upload Frida Patched APK
        uses: actions/upload-artifact@v4
        with:
          name: frida-injected-apk
          path: original/dist/original-aligned-debugSigned.apk
