name: Frida Gadget Injector (Full Automation - Direct)

on:
  # This workflow will run automatically whenever code is pushed to your repository.
  push:
    branches:
      - main  # You can change this to your default branch if it's not 'main'

jobs:
  patch-apk:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows writing to the repository for artifacts.
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Python
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies (frida-gadget)
        run: |
          pip install frida-gadget
          
      - name: Install apktool
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
          chmod +x apktool.jar
          sudo mv apktool.jar /usr/local/bin/apktool.jar
          echo '#!/bin/bash' | sudo tee /usr/local/bin/apktool > /dev/null
          echo 'java -jar /usr/local/bin/apktool.jar "$@"' | sudo tee -a /usr/local/bin/apktool > /dev/null
          sudo chmod +x /usr/local/bin/apktool

      - name: Download APK from Hardcoded URL
        run: |
          APK_URL="https://files.catbox.moe/qswufu.apk" # <--- REPLACE THIS WITH YOUR APK URL
          curl -L -o original.apk "$APK_URL"
          
      - name: Run Frida Gadget injection
        id: frida_inject
        run: |
          # Added the recommended recompile option to fix the apktool error
          frida-gadget original.apk --arch arm64 --recompile-opts "--use-aapt2"
          echo "PATCHED_APK=original-patched.apk" >> $GITHUB_ENV

      - name: Set up Android SDK for apksigner
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          ndk: 23.1.7779620
          
      - name: Generate Keystore for Signing
        run: |
          KEYSTORE_PASS="mysecurepassword" # <--- REPLACE THIS WITH YOUR PASSWORD
          KEY_ALIAS="mykey"
          
          keytool -genkey -v -keystore my-release-key.jks \
          -storepass "$KEYSTORE_PASS" \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias "$KEY_ALIAS" \
          -dname "CN=Frida Patch, OU=CI/CD, O=Automation, L=GitHub, S=Actions, C=US" \
          -keypass "$KEYSTORE_PASS"
          
      - name: Sign the Patched APK
        id: sign_apk
        run: |
          KEYSTORE_PASS="mysecurepassword" # <--- REPLACE THIS WITH YOUR PASSWORD
          apksigner sign --ks my-release-key.jks --ks-pass pass:"$KEYSTORE_PASS" --out "frida-patched-signed.apk" "$PATCHED_APK"
          
      - name: Upload Frida Patched APK
        uses: actions/upload-artifact@v4
        with:
          name: frida-injected-apk
          path: frida-patched-signed.apk
